GET http://localhost:4004/odata/v4/CatalogService


###Read service metadata
GET http://localhost:4004/odata/v4/CatalogService/$metadata


###Get Top 2 employees
GET http://localhost:4004/odata/v4/CatalogService/VehicleSet?$top=2

###POST Call - Create new employee
POST http://localhost:4004/odata/v4/CatalogService/VehicleSet
Content-Type: application/json

{
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C198E8DB",
      "platecode": "A",
      "platenum": "10003",
      "mobilenum": "1010101013",
      "name": "Third Cust",
      "noise": "2",
      "co2": "4"
}

###Get the employee which was created
http://localhost:4004/odata/v4/CatalogService/VehicleSet/02BD2137-0890-1EEA-A6C2-BB55C198E8DB

###Update employee Salary
PATCH http://localhost:4004/odata/v4/CatalogService/VehicleSet/02BD2137-0890-1EEA-A6C2-BB55C198E8DB
Content-Type: application/json

{
    "noise" : "3"
}

###Display All purchase orders
http://localhost:4004/odata/v4/CatalogService/VehicleSet

###Get single PO
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC34052


###GET main entity and associated entity together
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC34052?$expand=Items

###Boosting a order
POST http://localhost:4004/odata/v4/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC34052')/odata/v4/CatalogService.boost
Content-Type: application/json

{}

###Boosting a order
GET http://localhost:4004/odata/v4/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC34052')/odata/v4/CatalogService.largestOrder()

###Custom code - Entity GET
GET http://localhost:4004/mysrvdemo/ReadEmployeeSrv

###Custom code - Entity GET with dynamic where
GET http://localhost:4004/mysrvdemo/ReadEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C197A7FB